skip_final_snapshot: "#{is_dev}"

# cpu/memory sizing values can be found at:
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-tasks-size

service_sizing_default:
  min_capacity: 1
  max_capacity: 1
  cpu: 256
  memory: 512

service_sizing:
  bigboy:
    min_capacity: 1
    max_capacity: 1
    cpu: 512
    memory: 1024

db_sizing:
  some-rds:
    count: 0
    type: db.t2.micro
